documentando projeto calculadora
Joel-leal/calculadora pull request #16
Opened 2021-04-27 21:08 UTC by Joel-leal

Motivação: Documentar o projeto para que outros mentorandos possam se inteirar das descrições e interações aqui trabalhadas.

2021-04-27 21:32 UTC, Guilherme-BS approved these changes

2021-04-27 21:32 UTC, Guilherme-BS commented on README.md
> +## Motivação
doido

2021-04-27 21:35 UTC, Guilherme-BS requested changes

2021-04-27 21:35 UTC, Guilherme-BS commented on README.md
> +<a href="https://www.w3schools.com/html/"> W3 School - HTML5</a>
trocar links para formato markdown de link https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

2021-04-29 00:30 UTC, Joel-leal commented on README.md
> +<a href="https://www.w3schools.com/html/"> W3 School - HTML5</a>
link alterado

2021-04-29 21:04 UTC, marco-souza requested changes
Vamos tentar dar preferencia para a formatação do markdown no lugar de usar HTML.

2021-04-29 21:04 UTC, marco-souza commented on README.md
> +Acesse: <a href="https://joel-leal.github.io/calculadora/"> PodCalcular</a>
faltou alterar esse link

2021-04-29 21:04 UTC, marco-souza commented on projCalc.md
> +<a href="https://www.youtube.com/watch?v=Ejkb_YpuHWs&list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n"> Curso em vídeo - HTML5 e CSS3</a>
faltou os links desse arquivo tbm

2021-04-29 21:04 UTC, marco-souza commented on projCalc.md
> +<p align="left"> <a href="https://www.w3.org/html/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40
Existe um jeito de adicionar imagens no Markdown, mas não sei se tem como definir o tamanho dela. Veja se é possivel, se não for pode deixar como está:

https://docs.pipz.com/central-de-ajuda/learning-center/guia-basico-de-markdown

2021-04-30 17:59 UTC, Joel-leal commented on projCalc.md
> +<p align="left"> <a href="https://www.w3.org/html/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40
Vi as configurações para imagens, mas elas se arremetem ao código html/css. https://qastack.com.br/programming/14675913/changing-image-size-in-markdown

2021-04-30 18:08 UTC, marco-souza commented on projCalc.md
> +<p align="left"> <a href="https://www.w3.org/html/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40
Sim, mas á ideia seria justamente não usar HTML, e dar preferencia pro markdown. Elas ficaram no tamanho certo com markdown? Se sim, vamos manter ela, é mais legivel que o HTML

2021-04-30 18:42 UTC, Joel-leal commented on projCalc.md
> +<p align="left"> <a href="https://www.w3.org/html/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40
Não, elas ficam estouram na página. Acho que dá pra tirar a imagem também.

2021-04-30 20:10 UTC, marco-souza requested changes

2021-04-30 20:10 UTC, marco-souza commented on projCalc.md
> +<a href="https://www.devmedia.com.br/javascript/"> DEVMEDIA </a>
ta faltando alterar os links desse arquivo

2021-05-03 14:32 UTC, marco-souza approved these changes

2021-05-03 14:33 UTC, merged