Separando style-menu
Joel-leal/calculadora pull request #22
Opened 2021-05-18 17:25 UTC by Joel-leal

##Motivação

Para facilitar a manutenção das configurações e formatação do projeto, há a necessidade, nesse momento, de separar a folha de estilo referente ao menu e adicionar em todas as páginas.

2021-05-19 12:59 UTC, marco-souza requested changes
Bem melhor a história de commit, o que não fez sentido foi o ultimo  que resolve conflitos. Ele está apenas removendo a função de calculo, que poderia ser usada no JS e deixaria bem mais facil de ler.

Acho que podemos voltar com essa função (não necessariamente o arquivo) para deixar o código mais legível.

2021-05-19 12:59 UTC, marco-souza commented on functionArithmetic.js
> +      result = numberPrimary / numberSecondary;
não precisamos dessa variável `result`, podemos apenas retornar o resultado da operação, em cada `case`

2021-05-19 12:59 UTC, marco-souza commented on functionArithmetic.js
> +      result = numberPrimary / numberSecondary;
não precisamos dessa variável `result`, podemos apenas retornar o resultado da operação, em cada `case`

2021-05-19 12:59 UTC, marco-souza commented on style-menu.css
> +.navbar {
Só alegria esse css viu :)

2021-05-19 12:59 UTC, marco-souza commented on script.js
> +      break;
Podemos só chamar a função de calculo aqui definindo o valor de `displayTest`.

2021-05-19 12:59 UTC, marco-souza commented on index.html
> +        <div class="item3"id="cinzaClaro" id=>&
Acho que esse `id=` ta sobrando. Além disso, se o `cinzaClaro` é usado em mais de um lugar ele deve ser uma **class**, não um **id**. 

O ID tem que ser único na aplicação inteira, se for usar em mais de um lugar, crie uma `class`.

2021-05-19 12:59 UTC, marco-souza commented on index.html
> +        <div class="item3"id="cinzaClaro" id=>&
Essa div também não está fechando, e não tem `onclick`

2021-05-19 12:59 UTC, marco-souza commented on colaboradores/colaboradores.html
> -    <link rel="stylesheet" href="colaboradores.css" />
acho que podemos remover o arquivo de CSS, dado que não é mais utilizado

2021-05-19 12:59 UTC, marco-souza commented on conversor/styleConversor.css
> +.bloc-distance {
Esse arquivo só tem isso? Podemos mover a definição do `bloc-distance` para o arquivo principal de estilos e deletar esse daqui

2021-05-19 12:59 UTC, marco-souza commented on conversor/styleConversor.css
> +.bloc-distance {
Além disso, o nome não me parece certo, o que essa classe deveria fazer?

2021-05-19 16:10 UTC, Joel-leal commented on conversor/styleConversor.css
> +.bloc-distance {
Então, eu pensei em adicionar essa formatação no documento do style.css mas pensei que essa página vai existir para formatações futuras apenas para estilizar essa página.

2021-05-19 16:11 UTC, Joel-leal commented on colaboradores/colaboradores.html
> -    <link rel="stylesheet" href="colaboradores.css" />
Sim, irei excluir.

2021-05-19 16:17 UTC, Joel-leal commented on index.html
> +        <div class="item3"id="cinzaClaro" id=>&
Vou corrigir esse ID para uma class que puxará a formatação para todos com essa propriedade.

2021-05-19 16:53 UTC, marco-souza commented on conversor/styleConversor.css
> +.bloc-distance {
A gente é muito ruim em prever futuro, então vamos fazer sempre o que for mais simples de mudar. Nesse caso, seria mais facil criar um novo arquivo quando se mostrar necessário, do que manter um arquivo que pode não ser necessário.

2021-05-19 21:52 UTC, marco-souza approved these changes
Seria melhor se não usassemos a pasta `index`, dado que é um nome convencional de arquivos html e js, mas isso não é um problema que inviabiliza o merge. Podemos fazer em outra PR

2021-05-19 22:11 UTC, marco-souza approved these changes

2021-05-20 15:18 UTC, Joel-leal commented on functionArithmetic.js
> +      result = numberPrimary / numberSecondary;
Vou ver como fazer isso.

2021-05-20 15:18 UTC, merged